module.exports = [
  {
    id: 1,
    category: "man",
    bestSeller: true,
    name: "ZIP MOCK NECK T-SHIRT",
    description: "Mock neck T-shirt with front zip closure and short sleeves",
    price: 40,
    imageName: "zipBlack",
  },
  {
    id: 2,
    category: "man",
    bestSeller: false,
    name: "ZIP MOCK NECK T-SHIRT",
    description: "Mock neck T-shirt with front zip closure and short sleeves",
    price: 40,
    imageName: "zipBlue",
  },
  {
    id: 3,
    category: "man",
    bestSeller: false,
    name: "ZIP MOCK NECK T-SHIRT",
    description: "Mock neck T-shirt with front zip closure and short sleeves",
    price: 40,
    imageName: "zipGreen",
  },
  {
    id: 4,
    category: "man",
    bestSeller: false,
    name: "ZIP MOCK NECK T-SHIRT",
    description: "Mock neck T-shirt with front zip closure and short sleeves",
    price: 40,
    imageName: "zipWhite",
  },

  {
    id: 5,
    category: "man",
    bestSeller: true,
    name: "COMBINATION PRINT T-SHIRT",
    description:
      "Round neck T-shirt with short sleeves. All-over contrasting print details.",
    price: 40,
    imageName: "combination",
  },
  {
    id: 6,
    category: "man",
    bestSeller: false,
    name: "COMBINATION BASKETBALL T-SHIRT",
    description:
      "Round neck T-shirt with short sleeves. Contrasting graphic prints at front and back.",
    price: 45,
    imageName: "print",
  },
  {
    id: 7,
    category: "man",
    bestSeller: false,
    name: "PRINT T-SHIRT PARIS",
    description:
      "Round neck T-shirt with short sleeves. Contrasting graphic prints at front and back.",
    price: 50,
    imageName: "paris",
  },
  {
    id: 8,
    category: "man",
    bestSeller: false,
    name: "EMBROIDERED SHIRT",
    description:
      "Round neck T-shirt with short sleeves. Contrasting graphic prints at front and back.",
    price: 40,
    imageName: "embroidered",
  },
  {
    id: 9,
    category: "man",
    bestSeller: true,
    name: "TEXT PRINT T-SHIRT",
    description:
      "Round neck T-shirt with short sleeves. Contrasting graphic prints at front and back.",
    price: 40,
    imageName: "black",
  },
  {
    id: 10,
    category: "man",
    bestSeller: false,
    name: "Graphic PRINT T-SHIRT",
    description:
      "Round neck T-shirt with short sleeves. Contrasting graphic prints at front and back.",
    price: 40,
    imageName: "graphic",
  },
  {
    id: 11,
    category: "man",
    bestSeller: true,
    name: "Graphic PRINT T-SHIRT",
    description:
      "Round neck T-shirt with short sleeves. Contrasting graphic prints at front and back.",
    price: 40,
    imageName: "taupe",
  },
  {
    id: 12,
    category: "man",
    bestSeller: false,
    name: "Graphic PRINT T-SHIRT",
    description:
      "Round neck T-shirt with short sleeves. Front contrast prints of embroidery.",
    price: 40,
    imageName: "black2",
  },
  {
    id: 13,
    category: "woman",
    bestSeller: true,
    name: "VENTED COTTON T-SHIRT",
    description:
      "T-shirt made of 100% cotton. Round neck and short sleeves. Side vents at hem.",
    price: 32,
    imageName: "ventedBlack",
  },
  {
    id: 14,
    category: "woman",
    bestSeller: false,
    name: "VENTED COTTON T-SHIRT",
    description:
      "T-shirt made of 100% cotton. Round neck and short sleeves. Side vents at hem.",
    price: 32,
    imageName: "ventedBlue",
  },
  {
    id: 15,
    category: "woman",
    bestSeller: true,
    name: "VENTED COTTON T-SHIRT",
    description:
      "T-shirt made of 100% cotton. Round neck and short sleeves. Side vents at hem.",
    price: 32,
    imageName: "ventedTaupe",
  },
  {
    id: 16,
    category: "woman",
    bestSeller: true,
    name: "SHORT SLEEVE RIBBED T-SHIRT",
    description: "Round neck T-shirt with short sleeves. Scalloped trim",
    price: 32,
    imageName: "second",
  },
  {
    id: 17,
    category: "woman",
    bestSeller: false,
    name: "SHORT SLEEVE RIBBED T-SHIRT",
    description: "Round neck T-shirt with short sleeves. Scalloped trim",
    price: 32,
    imageName: "third",
  },
  {
    id: 18,
    category: "woman",
    bestSeller: false,
    name: "SHORT SLEEVE RIBBED T-SHIRT",
    description: "Round neck T-shirt with short sleeves. Scalloped trim",
    price: 32,
    imageName: "fourth",
  },
  {
    id: 19,
    category: "woman",
    bestSeller: true,
    name: "T-SHIRT WITH BUTTONS",
    description:
      "Round neck T-shirt with short sleeves. Side metal button detail.",
    price: 30,
    imageName: "woman",
  },
  {
    id: 20,
    category: "woman",
    bestSeller: false,
    name: "V-NECK T-SHIRT",
    description:
      "T-shirt made of 100% cotton with V-neck and short sleeves with dropped shoulders.",
    price: 30,
    imageName: "vneck",
  },
  {
    id: 21,
    category: "woman",
    bestSeller: true,
    name: "WASHED CROP TOP",
    description:
      "Due to the dyeing process, the print on each item is unique and special and may differ slightly from the one pictured.",
    price: 30,
    imageName: "washed",
  },
  {
    id: 22,
    category: "woman",
    bestSeller: true,
    name: "HALTERNECK BODYSUIT",
    description: "Halter neck bodysuit. Button snap button closure",
    price: 30,
    imageName: "asia",
  },
];
